apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: default
spec:
  selector:
    app: portfolio
  type: NodePort
  ports:
    - port: 1234
      targetPort: 3000
      nodePort: 30000